name: Test Secret Condition

on: workflow_dispatch # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Existence
        # The line we are testing
        if: ${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 != '' }}
        run: echo "SECRET EXISTS AND IS NOT EMPTY!"

      - name: Secret Does Not Exist or is Empty
        # Test the opposite condition
        if: ${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 == '' }}
        run: echo "SECRET DOES NOT EXIST OR IS EMPTY."

      - name: Always Run
        run: echo "This step always runs."
